package dev.fathony.tired

import com.github.gradle.node.npm.task.NpmTask
import dev.fathony.tired.icons.IconsExtension
import dev.fathony.tired.internal.readResource
import dev.fathony.tired.webassets.ToolchainPart
import dev.fathony.tired.webassets.WEB_ASSETS_BUILD_DIR
import dev.fathony.tired.webassets.WebAssetsExtension
import org.jetbrains.kotlin.gradle.dsl.KotlinJvmProjectExtension

/**
 * Lucide icons: one sprite, the `Icons` enum and, with KTML, the `<icon>` tag.
 */
plugins {
    id("dev.fathony.tired.web-assets")
}

val icons = extensions.create<IconsExtension>("icons")
the<WebAssetsExtension>().toolchainParts.add(ToolchainPart.ICONS)

val webAssetsDir = layout.buildDirectory.dir(WEB_ASSETS_BUILD_DIR)

val npmBuildSvg =
    tasks.register<NpmTask>("npmBuildSvg") {
        dependsOn(tasks.named("npmInstall"))
        args.set(
            icons.constants.map { constants ->
                listOf(
                    "run",
                    "build:svg",
                    "--",
                    "--icons",
                    constants.keys.sorted().joinToString(","),
                    "--outdir",
                    "dist/icons",
                    "--meta",
                    "dist/meta/icons.meta",
                )
            },
        )
        inputs.property("icons", icons.constants)
        inputs.files(tasks.named("prepareWebAssetsToolchain"))
        outputs.dir(webAssetsDir.map { it.dir("dist/icons") })
        outputs.file(webAssetsDir.map { it.file("dist/meta/icons.meta") })
        onlyIf("icons are registered") { icons.constants.get().isNotEmpty() }
    }

val generateIcons =
    tasks.register("generateIcons") {
        val constants = icons.constants
        inputs.property("icons", constants)

        val outputDir = layout.buildDirectory.dir("generated/source/icons")
        outputs.dir(outputDir)

        doLast {
            val byConstant = constants.get().entries.groupBy({ it.value }, { it.key })
            val clashes = byConstant.filterValues { it.size > 1 }
            if (clashes.isNotEmpty()) {
                val detail =
                    clashes.entries.joinToString("; ") { (constant, lucideIcons) ->
                        "${lucideIcons.sorted().joinToString(" and ")} both map to '$constant'"
                    }
                throw GradleException("Clashing icon constants: $detail. Pass alias = \"...\" to disambiguate.")
            }

            val entries =
                byConstant.entries
                    .sortedBy { it.key }
                    .joinToString("\n") { (constant, lucideIcons) ->
                        "    $constant(\"${lucideIcons.single()}\"),"
                    }

            val content =
                """
                |enum class Icons(
                |    val lucideIcon: String,
                |) {
                |$entries
                |}
                """.trimMargin()

            val outDir = outputDir.get().asFile
            outDir.mkdirs()
            outDir.resolve("Icons.kt").writeText(content)
        }
    }

extensions.configure<KotlinJvmProjectExtension> {
    sourceSets.named("main") {
        kotlin.srcDir(generateIcons)
    }
}

tasks.named("generateAssetManifest") {
    dependsOn(npmBuildSvg)
    inputs.files(npmBuildSvg)
}

tasks.named<ProcessResources>("processResources") {
    from(webAssetsDir.map { it.dir("dist/icons") }) { into("static") }
}

/**
 * KTML only reads `src/main/ktml`, so the tag is written there, into a folder that ignores itself.
 */
pluginManager.withPlugin("dev.ktml.gradle") {
    val iconTagDir = layout.projectDirectory.dir("src/main/ktml/tired")
    val iconTag = readResource("ktml/icon.ktml").decodeToString()

    val generateIconTag =
        tasks.register("generateIconTag") {
            inputs.property("template", iconTag)
            outputs.dir(iconTagDir)

            doLast {
                val dir = iconTagDir.asFile
                dir.mkdirs()
                dir.resolve(".gitignore").writeText("# Generated by the tired Gradle plugin.\n*\n")
                dir.resolve("icon.ktml").writeText(iconTag)
            }
        }

    tasks.matching { it.name == "generateKtml" }.configureEach { dependsOn(generateIconTag) }
    /**
     * Copied along with `src/main/ktml` for PostCSS.
     */
    tasks.named("syncWebAssetsSources") { dependsOn(generateIconTag) }
}
